# On push to main, checkout deploy branch and works in it.

name: Deploy Wasm App

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  ref: refs/heads/deploy
  # for trunk build
  # GitHub Pages URL will be
  # https://<user>.github.io/playsv/
  public_url: /playsv/

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
          fetch-depth: 0
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Git Setup
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge from main
        run: |
          git merge --no-ff ${GITHUB_SHA}

      - name: Tools
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Build
        working-directory: ./client
        run: |
          trunk build --release --public-url ${{ env.public_url }}

      - name: Remove Old Data and Move
        run: |
          git rm --ignore-unmatch ./docs/?*.*
          mv ./client/dist/* ./docs/

      - name: Git Add
        run: |
          git add ./docs

      - name: Git Commit
        continue-on-error: true
        run: |
          git commit -m "Update for ${GITHUB_REF} ${GITHUB_SHA}" -m "Automatic push by github actions"

      - name: Git Push
        run: |
          git push origin HEAD:${{ env.ref }}
