name: Rust

on: [push, pull_request]

env:
  # treat warnings as error
  # RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk --locked

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk --locked

      - name: Build
        run: cargo build --release --verbose
