name: Rust Build

on: [push, pull_request]

env:
  # treat warnings as error
  # RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk --locked

      - name: Format
        run: cargo fmt -- --check

      - name: Format Client
        working-directory: ./client
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Clippy Client
        working-directory: ./client
        run: cargo clippy --all-targets --all-features

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk --locked

      - name: Build
        run: cargo build --release --verbose
